id: os_application_deny_list
title: "Deny Organization-Defined Prohibited Applications"
discussion: |
  Applications which are not permitted for use by the organization _MUST_ be defined in a _SHOULD_VALUEONDEMAND_ list and applied to the device via MDM.
check: ' '
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-93471-1
  800-53r5:
    - N/A
  indigo:
    - ANNEX D (Section 5.8 - App-Installation)
    - ANNEX N
iOS:
  - "17.0"
tags:
  - ios
  - manual
  - indigo_base
  - indigo_high
supervised: true
mobileconfig: false # Set to true when implementing
mobileconfig_info:
  com.apple.applicationaccess:
    blockedAppBundleIDs: # Add bundle identifiers below
      - bundleID1
      - bundleID2
    
