id: os_system_settings_find_my_device_disable
title: "Disable Find My Device"
discussion: |
  The Find My service _SHOULD_ be disabled, if decided by the CISO.

  A Mobile Device Management (MDM) solution _SHOULD_ be used to carry out remote locking and wiping instead of Apple's Find My service.

  Apple's Find My service uses a personal AppleID for authentication. Organizations should rely on MDM solutions, which have much more secure authentication requirements, to perform remote lock and remote wipe.
check: |
  Check your MDM to ensure that Find My Device has been disabled on the iOS endpoint.
result:
  string: "false"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  800-53r5:
    - N/A
  indigo:
    - ANNEX K
iOS:
  - "17.0"
tags:
  - ios
  - indigo_high
supervised: true
mobileconfig: true
mobileconfig_info:
  com.apple.applicationaccess:
    allowFindMyDevice: false
